Add unsqueeze_
OpenMined/PySyft pull request #4471
Opened 2020-08-24 22:30 UTC by gmuraru

## Description
**Attention**: This needs to be merged after [this](https://github.com/OpenMined/PySyft/pull/4470)
Fixes #4458 
Added the possibility to use ```unsqueeze_``` as remote operation in the syft 0.3.0 version.

## How has this been tested?
- The tests from the allow commands list

## Checklist
- [x] I have followed the [Contribution Guidelines](https://github.com/OpenMined/.github/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/OpenMined/.github/blob/master/CODE_OF_CONDUCT.md)
- [x] I have commented my code following the [OpenMined Styleguide](https://github.com/OpenMined/.github/blob/master/STYLEGUIDE.md)
- [x] I have labeled this PR with the relevant [Type labels](https://github.com/OpenMined/.github/labels?q=Type%3A)
- [x] My changes are covered by tests

2020-08-24 23:48 UTC, iamtrask commented on src/syft/lib/torch/allowlist.py
> -# allowlist['torch.Tensor.true_divide_'] = #
Do inline operations return torch.Tensor? I thought they return None, yes?

2020-08-24 23:48 UTC, iamtrask requested changes
Quick Q inline

2020-08-24 23:59 UTC, madhavajay commented on src/syft/lib/torch/allowlist.py
> -# allowlist['torch.Tensor.true_divide_'] = #
Seems like they always return "self"

<img width="710" alt="Screen Shot 2020-08-25 at 9 57 29 am" src="https://user-images.githubusercontent.com/2882739/91107766-6d945f80-e6b9-11ea-9d21-599cb787c2fa.png">
<img width="574" alt="Screen Shot 2020-08-25 at 9 58 48 am" src="https://user-images.githubusercontent.com/2882739/91107832-99174a00-e6b9-11ea-83eb-b74307b4cb3f.png">

2020-08-25 00:00 UTC, madhavajay commented
LGTM!

2020-08-25 00:02 UTC, madhavajay commented
> Quick Q inline

sure

2020-08-25 00:07 UTC, madhavajay commented
Going to merge and continue on my branch.

2020-08-25 00:07 UTC, merged