integrate xgboost
OpenMined/PySyft pull request #5473
Opened 2021-04-14 12:56 UTC by Param-29

## Description

Integrating xgboost into syft. 

Following are the machine learning classes to be integrated. 

- [x] `Booster` class
- [ ]  `XGBRegressor`
- [ ] `XGBClasifier`

## Affected Dependencies
None:

## How has this been tested?
- Added in unit tests to check the changes

## Checklist
- [x] I have followed the [Contribution Guidelines](https://github.com/OpenMined/.github/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/OpenMined/.github/blob/master/CODE_OF_CONDUCT.md)
- [x] I have commented my code following the [OpenMined Styleguide](https://github.com/OpenMined/.github/blob/master/STYLEGUIDE.md)
- [ ] I have labeled this PR with the relevant [Type labels](https://github.com/OpenMined/.github/labels?q=Type%3A)
- [x] My changes are covered by tests

2021-04-19 14:06 UTC, tudorcebere requested changes

2021-04-19 14:06 UTC, tudorcebere commented on tests/syft/lib/xgboost/model_test.py
> +    y_pred_classifier_remote = classifier.predict(X).get(root_client)
mixing .send with .get syntax

2021-04-20 07:11 UTC, Param-29 commented on tests/syft/lib/xgboost/model_test.py
> +    y_pred_classifier_remote = classifier.predict(X).get(root_client)
Updated, thanks!!

2021-04-21 14:49 UTC, tudorcebere approved these changes

2021-04-21 14:49 UTC, merged