inplace ops gc test
OpenMined/PySyft pull request #5503
Opened 2021-04-23 13:09 UTC by tudorcebere

## Description
Solves #4764

2021-04-29 17:46 UTC, gmuraru commented on tests/syft/core/pointer/garbage_collection/inplace_op_gc_test.py
> +    func(*args)  # inplace op
NITPICK: Maybe also add assert after the operation?

2021-04-29 17:46 UTC, gmuraru approved these changes
LGTM!

2021-04-30 01:03 UTC, madhavajay commented on tests/syft/core/pointer/garbage_collection/inplace_op_gc_test.py
> +    func(*args)  # inplace op
We need to check the return pointer of the Tensor op because it returns a second pointer to the same value.

2021-04-30 01:03 UTC, madhavajay requested changes
LGTM just need the tensor pointer return value checked.

2021-06-07 06:47 UTC, madhavajay approved these changes
LGTM!

2021-06-22 06:24 UTC, merged