Fix model serialization in MCFL python notebook (fixes #5460)
OpenMined/PySyft pull request #5520
Opened 2021-04-27 13:39 UTC by vvmnnnkv

## Description
Model serialization scheme was updated in the last moment before 0.5.0rc1, 
but I forgot to change it in part of the MCFL notebook that demonstrates low-level interaction with Grid where model ser-de was made "manually" not using syft routines.
This change doesn't affect any functionality.

## Affected Dependencies
List any dependencies that are required for this change.

## How has this been tested?
Ran create plan & execute plan notebooks against pygrid 0.5.0rc1

## Checklist
- [ ] I have followed the [Contribution Guidelines](https://github.com/OpenMined/.github/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/OpenMined/.github/blob/master/CODE_OF_CONDUCT.md)
- [ ] I have commented my code following the [OpenMined Styleguide](https://github.com/OpenMined/.github/blob/master/STYLEGUIDE.md)
- [ ] I have labeled this PR with the relevant [Type labels](https://github.com/OpenMined/.github/labels?q=Type%3A)
- [ ] My changes are covered by tests

2021-04-27 16:12 UTC, tudorcebere approved these changes

2021-04-27 19:12 UTC, tudorcebere approved these changes

2021-04-28 08:07 UTC, madhavajay commented
@vvmnnnkv Can we get these changes added to the `tests/syft/core/fl/model-centric/mcfl_create_execute_plan_test.py` since its a combination of both notebooks?

2021-04-28 08:08 UTC, madhavajay requested changes
Looks good just need to make sure it passes in the test suite as well.

2021-04-28 08:08 UTC, madhavajay commented on examples/federated-learning/model-centric/mcfl_create_plan.ipynb
> +    "from syft.federated.model_serialization import deserialize_model_params\n",
Add these changes to `tests/syft/core/fl/model-centric/mcfl_create_execute_plan_test.py`?

2021-04-28 08:15 UTC, koenvanderveen approved these changes

2021-08-05 08:11 UTC, madhavajay commented
Closing due to inactivity.

2021-08-05 08:11 UTC, closed without merging