Serde patch
OpenMined/PySyft pull request #5545
Opened 2021-05-06 10:27 UTC by tudorcebere

## Description
Please include a summary of the change, the motivation, and any additional context that will help others understand your PR. If it closes one or more open issues, [please tag them as described here](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

## Affected Dependencies
List any dependencies that are required for this change.

## How has this been tested?
- Describe the tests that you ran to verify your changes.
- Provide instructions so we can reproduce.
- List any relevant details for your test configuration.

## Checklist
- [ ] I have followed the [Contribution Guidelines](https://github.com/OpenMined/.github/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/OpenMined/.github/blob/master/CODE_OF_CONDUCT.md)
- [ ] I have commented my code following the [OpenMined Styleguide](https://github.com/OpenMined/.github/blob/master/STYLEGUIDE.md)
- [ ] I have labeled this PR with the relevant [Type labels](https://github.com/OpenMined/.github/labels?q=Type%3A)
- [ ] My changes are covered by tests

2021-05-06 11:08 UTC, madhavajay commented on src/syft/core/pointer/pointer.py
> -        time.sleep(0.1)
This might actually make things slower if you are using the request_handlers.

2021-05-13 03:15 UTC, madhavajay commented
@tudorcebere This looks like it breaks the Grid unit tests. We could hold this one off until we go monorepo, or you could checkout the PyGrid repo into the root syft dir and then run the tests the same way CI does and make a PR for Grid that brings them together.

2021-05-13 03:16 UTC, madhavajay requested changes
This breaks PyGrid Unit tests, so we should make sure theres a PR on the other side which integrates these changes.

2021-05-13 08:11 UTC, tudorcebere commented
I'm fine with mono repo first, then this change.

2021-06-28 23:01 UTC, madhavajay commented
@tudorcebere can we update this with the mono repo and get it merged before there are too many new post `0.5.0` changes.

2021-08-05 08:11 UTC, madhavajay commented
@tudorcebere I definitely still want to see this PR. Lets discuss when you have cycles again.

2021-09-03 09:01 UTC, closed without merging