Update / Fix roles
OpenMined/PySyft pull request #6006
Opened 2021-09-27 09:11 UTC by IonesioJunior

2021-09-28 13:29 UTC, tcp requested changes
Good stuff removing groups Ionesio!

There are 2 permissions that are still missing: `Can Upload Legal Documents` and `Can Edit Domain Settings`.

2021-09-28 13:29 UTC, tcp commented on packages/grid/backend/grid/api/roles/roles.py
> +    can_upload_data: bool = Body(False, example="false"),
Missing "Can Upload Legal Documents"

2021-09-28 13:29 UTC, tcp commented on packages/grid/backend/grid/api/roles/roles.py
> +    can_upload_data: bool = Body(False, example="false"),
Missing "Can Edit Domain Settings"

2021-09-29 16:27 UTC, IonesioJunior commented on packages/grid/backend/grid/api/roles/roles.py
> +    can_upload_data: bool = Body(False, example="false"),
Fixed by 4d75037

2021-09-29 17:08 UTC, tcp approved these changes

2021-09-29 17:08 UTC, merged