update hagrid install instruction
OpenMined/PySyft pull request #6751
Opened 2022-09-14 09:03 UTC by bitsofsteve

resolves #6724

2022-09-14 10:15 UTC, shubham3121 approved these changes

2022-09-14 11:04 UTC, iamtrask requested changes
I'm not sure it's a requirement but conventionally I believe the "-U" goes after the end of the command (so after the word "hagrid")

2022-09-14 11:18 UTC, bitsofsteve commented
> I'm not sure it's a requirement but conventionally I believe the "-U" goes after the end of the command (so after the word "hagrid")

@iamtrask oh good to know, but looking at the documentation from pip here: https://pip.pypa.io/en/stable/installation/#upgrading-pip and how it's used it seems `pip install -U SomePackage` is also pretty standard.

2022-09-15 02:25 UTC, madhavajay approved these changes
Great work! 🙌🏽

2022-09-15 02:25 UTC, merged