Fix Linux Docker instructions
OpenMined/PySyft pull request #6794
Opened 2022-09-29 14:22 UTC by IonesioJunior

## Checklist
- [ ] Check if the user is root and warns them that using hagrid in root might cause issues if they run it later without root.
- [ ] Check if the user they are using is in the sudo group in the dependency checker on Linux to make sure they have permission ahead of time.
- [ ] Check if they are in the docker group and if not, ask them to add themselves. Here we will need to test/make sure that either hagrid (through subprocess shells) or if there is some way we can restart the session so that we can access docker from their user without logging out and logging back in again.

2022-10-09 21:24 UTC, IonesioJunior commented
**Error message when docker binary is not found**
![docker_uninstalled](https://user-images.githubusercontent.com/26658472/194780019-5e1ffa47-a798-44fb-afea-bf3e2c5ce8ca.png)


**Error message when docker binary is found but the current user is not allowed to execute docker commands (Linux)**
![user_permission_error](https://user-images.githubusercontent.com/26658472/194780071-a57c7647-cc6f-4ffb-aa49-143783dbbf1f.png)

2022-10-12 12:43 UTC, shubham3121 requested changes

2022-10-12 12:43 UTC, shubham3121 commented on packages/hagrid/hagrid/deps.py
> +        cmd = "docker --version"
@IonesioJunior we want to use `docker info` as it checks if docker is running or not on windows and mac and starts docker incase of ubuntu. `docker --version` doesn't detect that. 

I think we need to fix the order of checking sudo and docker running status. First check docker has sudo status and then check docker running status.

2022-10-12 12:43 UTC, shubham3121 commented on packages/hagrid/hagrid/deps.py
> +            user_allowed, permission_msg = allowed_to_run_docker()
here we can swap the order of these method calls. 
So first call `allowed_to_run_docker()` and then call `docker_running` method.

2022-10-12 14:54 UTC, shubham3121 approved these changes
This is fantastic 🙌🏾 
Great work @IonesioJunior !! 🎉

2022-10-12 14:54 UTC, merged