added signing_key to serde
OpenMined/PySyft pull request #7293
Opened 2023-02-07 07:24 UTC by rasswanth-s

## Description
Please include a summary of the change, the motivation, and any additional context that will help others understand your PR. If it closes one or more open issues, [please tag them as described here](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

## Affected Dependencies
List any dependencies that are required for this change.

## How has this been tested?
- Describe the tests that you ran to verify your changes.
- Provide instructions so we can reproduce.
- List any relevant details for your test configuration.

## Checklist
- [ ] I have followed the [Contribution Guidelines](https://github.com/OpenMined/.github/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/OpenMined/.github/blob/master/CODE_OF_CONDUCT.md)
- [ ] I have commented my code following the [OpenMined Styleguide](https://github.com/OpenMined/.github/blob/master/STYLEGUIDE.md)
- [ ] I have labeled this PR with the relevant [Type labels](https://github.com/OpenMined/.github/labels?q=Type%3A)
- [ ] My changes are covered by tests

2023-02-07 23:08 UTC, madhavajay requested changes
Lets discuss

2023-02-08 01:42 UTC, rasswanth-s commented on packages/syft/src/syft/core/node/common/node.py
> +    def get_api(self, signing_key: Optional[SyftSigningKey] = None) -> SyftAPI:
MAYBE: Lets make the signing_key a mandatory argument, so we could enforce them to always pass the signing key of the user requesting the api.?

2023-02-08 01:43 UTC, rasswanth-s commented on packages/syft/src/syft/grid/client/grid_connection.py
> -        obj.api_url = f"{str(self.base_url)}/syft/new_api_call"
Q: Why have we removed it ?

2023-02-08 01:43 UTC, rasswanth-s commented on packages/syft/src/syft/oblv/deployment_client.py
> -        obj.api_url = f"{self.__conn_string}/worker/syft_api_call"
Q: Why have we removed it?

2023-02-08 01:44 UTC, rasswanth-s commented on packages/syft/src/syft/core/node/common/node.py
>          return SyftAPI.for_user(node_uid=self.id, signing_key=self.signing_key)
NITPICK : self.signing_key --> _signing_key

2023-02-15 06:06 UTC, closed without merging