added unit tests
OpenMined/PySyft pull request #7460
Opened 2023-03-26 21:30 UTC by letv3

## Description
Please include a summary of the change, the motivation, and any additional context that will help others understand your PR. If it closes one or more open issues, [please tag them as described here](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

## Affected Dependencies
List any dependencies that are required for this change.

## How has this been tested?
- Describe the tests that you ran to verify your changes.
- Provide instructions so we can reproduce.
- List any relevant details for your test configuration.

## Checklist
- [ ] I have followed the [Contribution Guidelines](https://github.com/OpenMined/.github/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/OpenMined/.github/blob/master/CODE_OF_CONDUCT.md)
- [ ] I have commented my code following the [OpenMined Styleguide](https://github.com/OpenMined/.github/blob/master/STYLEGUIDE.md)
- [ ] I have labeled this PR with the relevant [Type labels](https://github.com/OpenMined/.github/labels?q=Type%3A)
- [ ] My changes are covered by tests

2023-03-28 19:52 UTC, letv3 commented
Marked `test_dataset_update` and `test_dataset_serach_action_ids` as **xfail** because it seams some corresponding functionality is not implemented.

2023-03-29 06:48 UTC, letv3 commented
Hey @shubham3121 @koenvanderveen  Can you please review the PR? 
Thanks

2023-03-29 11:28 UTC, shubham3121 requested changes
@letv3 left some comments. Feel free to reach out to me for any clarifications.

2023-03-29 11:28 UTC, shubham3121 commented on packages/syft/tests/syft/dataset/dataset_stash_test.py
> +    name_partition_key = QueryKeys(qks=NamePartitionKey).all[0]
To generate a Querykey from PartitionKey we can either:
`QueryKey.from_obj(partition_key=NamePartitionKey, obj='Dummy Name')`
or call
name_query_key = NamePartitionKey.with_obj('Dummy Name')  # pass in the value directly for the partition key
Or
@dataclass
class MockObj:
    name: str

obj = MockObj(name="Dummy Name")
name_query_key = NamePartitionKey.with_obj(obj)  # pass an object which has partition key as one of its class members.

Note: A QueryKey is has the attributes of the PartitionKey plus `value`, which holds the value.

You can refer to this test for [reference](https://github.com/OpenMined/PySyft/pull/7462/files#diff-39617657524bd6b2b22dfb196f13b928a252c0f4fd2ed76e5584bf7c85d996f3R82)

2023-03-29 11:28 UTC, shubham3121 commented on packages/syft/tests/syft/dataset/dataset_stash_test.py
> +def test_dataset_serach_action_ids(mock_dataset_stash, mock_dataset):
A Dataset is composed of a list of assets (see Asset class). This asset actual actually stores the data. `action_id` is the location of the asset in the ActionStore.

For reference:
https://github.com/OpenMined/PySyft/blob/dev/notebooks/api/0.8/00-load-data.ipynb

So to test this, we need to:
- create a asset and save it to ActionStore
- create a Dataset with Asset attached to it.
- save Dataset to store.
Now we can retrieve datasets for given action ids.

2023-04-05 07:18 UTC, madhavajay approved these changes
This is awesome work @letv3! 🙏

2023-04-05 07:19 UTC, merged