[Refactor] Fixing mypy issues of `service/dataset`
OpenMined/PySyft pull request #8464
Opened 2024-02-07 03:15 UTC by khoaguin

2024-02-07 13:22 UTC, kiendang requested changes

2024-02-07 13:22 UTC, kiendang commented on packages/syft/src/syft/service/dataset/dataset.py
> +        **data: Dict[str, Any],
```suggestion
        **data: Any,
```

`*args` and `**kwargs` should be typed as `*args: Any` and `**kwargs: Any`, not `*args: Tuple[Any]` and `**kwargs: Dict[str, Any]`. see #6791

2024-02-07 13:22 UTC, kiendang commented on packages/syft/src/syft/service/dataset/dataset.py
> +    def __init__(self, description: Optional[str] = "", **data: Dict[str, Any]) -> None:
```suggestion
    def __init__(self, description: Optional[str] = "", **data: Any) -> None:
```

2024-02-07 13:22 UTC, kiendang commented on packages/syft/src/syft/service/dataset/dataset.py
> +        **data: Dict[str, Any],
```suggestion
        **data: Any,
```

2024-02-12 03:09 UTC, khoaguin commented on packages/syft/src/syft/service/dataset/dataset.py
> +    def __init__(self, description: Optional[str] = "", **data: Dict[str, Any]) -> None:
Thanks @kiendang

2024-02-12 07:11 UTC, kiendang approved these changes

2024-02-14 09:14 UTC, merged