Documentataion for development with k8s
OpenMined/PySyft pull request #8805
Opened 2024-05-13 17:42 UTC by snwagh

## Description
Closes this [issue](https://github.com/OpenMined/Heartbeat/issues/1217)

2024-05-14 02:36 UTC, khoaguin commented
Hi @snwagh can we add the newly made commands to launch different types of nodes into the tutorial, for example:

1. For Launching a Domain
```zsh
CLUSTER_NAME=testdomain1 CLUSTER_HTTP_PORT=9082 tox -e dev.k8s.launch.domain
```
2. For Launching a Gateway
```zsh
CLUSTER_NAME=testgateway1 CLUSTER_HTTP_PORT=9081 tox -e dev.k8s.launch.gateway
```
3. For Launching a Enclave
```zsh
CLUSTER_NAME=testenclave1 CLUSTER_HTTP_PORT=9083 tox -e dev.k8s.launch.enclave
```
4. For launching nodes with `hotreload`:
```zsh
tox -e dev.k8s.domain -- hotreload
```

2024-05-14 14:59 UTC, snwagh commented
@khoaguin Great suggestion, added these.

2024-05-17 09:55 UTC, IrinaMBejan requested changes
This is excellent! Just a few nit comments.

2024-05-17 09:55 UTC, IrinaMBejan commented on notebooks/tutorials/deploy/07-deploy-devspace.ipynb
> +    "This guide is meant for developers trying to deploy PySyft locally on a Kubernetes cluster. PySyft is a powerful framework for privacy-preserving machine learning, and deploying it on Kubernetes
I think privacy-preserving ML is only a dimension of what one could do with PySyft - to keep the messaging uniform, I'd either extend it as `privacy-preserving data analysis and machine learning` or `conducting privacy-preserving research on non-public data`

2024-05-17 09:55 UTC, IrinaMBejan commented on notebooks/tutorials/deploy/07-deploy-devspace.ipynb
> +    "If you would like to a non-isolated install then install the dependencies using [brew](https://brew.sh/) as follows:   \n",
to do a*

2024-05-22 17:23 UTC, itstauq approved these changes

2024-05-30 13:30 UTC, IrinaMBejan approved these changes

2024-05-30 14:02 UTC, merged