Show requesting domain (for DistributedProject as well as base Requests)
OpenMined/PySyft pull request #8983
Opened 2024-06-27 14:56 UTC by snwagh

This changes the output to show the domain name at which the request was made. Tagging for PM review since I change the base object `Request`'s repr. The output looks as follows (Requested on added):

![Screenshot 2024-06-27 at 10 51 39 AM](https://github.com/OpenMined/PySyft/assets/10202935/859815a7-6015-4d45-84c4-756ec20ce95d)

2024-06-27 16:57 UTC, itstauq approved these changes
LGTM

2024-06-27 17:19 UTC, itstauq requested changes
Edit: On a closer look, I was wondering if we could directly patch the Request objects in DistributedProject.requests property? Otherwise merging this will change the Request object for existing single projects as well.

2024-06-27 18:27 UTC, snwagh commented
@itstauq Since the DistributedProjects uses the same objects inside it, I was wondering if this is a better fix as long as we run it by PM. It changes the Request object for the single projects too but it's just a change to the __repr__ so not a conflicting change IMO.

2024-06-28 17:30 UTC, snwagh commented
@itstauq To address your comment, added another commit that does not create a breaking change.

2024-07-02 04:05 UTC, madhavajay commented
Closing for now, we will move the domain information to Project code in this PR: https://github.com/OpenMined/PySyft/pull/8999

2024-07-02 04:05 UTC, closed without merging